apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: myapp-dev
resources:
- ../../myapp

patchesJSON6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: prometheus-example-app
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
